services:
  backend:
    build:
      context: .
    container_name: nestjs-music-application
    ports:
      - '127.0.0.1:3000:3000'
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: nest_music_postgres
    restart: always
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: fabricio
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestdb
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U fabricio -d nestdb']
      interval: 2s
      timeout: 5s
      retries: 15
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
